version: "3.9"
services:
  mongo:
    image: mongo:latest
    env_file:
      - ./mongo/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongodb_data_container:/data/database
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

volumes:
  mongodb_data_container:
